// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PlakDukkaniYonetimi.Core.Context;

#nullable disable

namespace PlakDukkaniYonetimi.Core.Migrations
{
    [DbContext(typeof(PlakDukkaniContext))]
    partial class PlakDukkaniContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PlakDukkaniYonetimi.Core.Models.Album", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AlbumAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CikisTarihi")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Fiyat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("IndirimOrani")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Sanatci")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("SatisDevamMi")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Albumler");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AlbumAdi = "Opus Eponymous",
                            CikisTarihi = new DateTime(2010, 10, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Fiyat = 120m,
                            Sanatci = "Ghost",
                            SatisDevamMi = false
                        },
                        new
                        {
                            Id = 2,
                            AlbumAdi = "Infestissumam",
                            CikisTarihi = new DateTime(2013, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Fiyat = 130m,
                            Sanatci = "Ghost",
                            SatisDevamMi = true
                        },
                        new
                        {
                            Id = 3,
                            AlbumAdi = "Meliora",
                            CikisTarihi = new DateTime(2015, 8, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Fiyat = 140m,
                            Sanatci = "Ghost",
                            SatisDevamMi = true
                        },
                        new
                        {
                            Id = 4,
                            AlbumAdi = "Prequelle",
                            CikisTarihi = new DateTime(2018, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Fiyat = 150m,
                            IndirimOrani = 10m,
                            Sanatci = "Ghost",
                            SatisDevamMi = true
                        },
                        new
                        {
                            Id = 5,
                            AlbumAdi = "Impera",
                            CikisTarihi = new DateTime(2022, 3, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Fiyat = 160m,
                            Sanatci = "Ghost",
                            SatisDevamMi = true
                        },
                        new
                        {
                            Id = 6,
                            AlbumAdi = "Rite Here Rite Now",
                            CikisTarihi = new DateTime(2024, 7, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Fiyat = 170m,
                            Sanatci = "Ghost",
                            SatisDevamMi = true
                        },
                        new
                        {
                            Id = 7,
                            AlbumAdi = "The Frail Tide",
                            CikisTarihi = new DateTime(2007, 4, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Fiyat = 110m,
                            Sanatci = "Be'lakor",
                            SatisDevamMi = false
                        },
                        new
                        {
                            Id = 8,
                            AlbumAdi = "Stone's Reach",
                            CikisTarihi = new DateTime(2009, 6, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Fiyat = 120m,
                            Sanatci = "Be'lakor",
                            SatisDevamMi = true
                        },
                        new
                        {
                            Id = 9,
                            AlbumAdi = "Of Breath and Bone",
                            CikisTarihi = new DateTime(2012, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Fiyat = 130m,
                            Sanatci = "Be'lakor",
                            SatisDevamMi = true
                        },
                        new
                        {
                            Id = 10,
                            AlbumAdi = "Vessels",
                            CikisTarihi = new DateTime(2016, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Fiyat = 140m,
                            IndirimOrani = 10m,
                            Sanatci = "Be'lakor",
                            SatisDevamMi = true
                        },
                        new
                        {
                            Id = 11,
                            AlbumAdi = "Coherence",
                            CikisTarihi = new DateTime(2021, 10, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Fiyat = 150m,
                            Sanatci = "Be'lakor",
                            SatisDevamMi = true
                        },
                        new
                        {
                            Id = 12,
                            AlbumAdi = "Väsen",
                            CikisTarihi = new DateTime(2024, 11, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Fiyat = 160m,
                            Sanatci = "Be'lakor",
                            SatisDevamMi = true
                        },
                        new
                        {
                            Id = 13,
                            AlbumAdi = "Lunar Strain",
                            CikisTarihi = new DateTime(1994, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Fiyat = 100m,
                            Sanatci = "In Flames",
                            SatisDevamMi = false
                        },
                        new
                        {
                            Id = 14,
                            AlbumAdi = "The Jester Race",
                            CikisTarihi = new DateTime(1996, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Fiyat = 110m,
                            Sanatci = "In Flames",
                            SatisDevamMi = false
                        },
                        new
                        {
                            Id = 15,
                            AlbumAdi = "Whoracle",
                            CikisTarihi = new DateTime(1997, 10, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Fiyat = 120m,
                            Sanatci = "In Flames",
                            SatisDevamMi = false
                        },
                        new
                        {
                            Id = 16,
                            AlbumAdi = "Colony",
                            CikisTarihi = new DateTime(1999, 5, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Fiyat = 130m,
                            Sanatci = "In Flames",
                            SatisDevamMi = true
                        },
                        new
                        {
                            Id = 17,
                            AlbumAdi = "Clayman",
                            CikisTarihi = new DateTime(2000, 7, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Fiyat = 140m,
                            Sanatci = "In Flames",
                            SatisDevamMi = true
                        },
                        new
                        {
                            Id = 18,
                            AlbumAdi = "Reroute to Remain",
                            CikisTarihi = new DateTime(2002, 9, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Fiyat = 150m,
                            Sanatci = "In Flames",
                            SatisDevamMi = true
                        },
                        new
                        {
                            Id = 19,
                            AlbumAdi = "Soundtrack to Your Escape",
                            CikisTarihi = new DateTime(2004, 3, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Fiyat = 160m,
                            Sanatci = "In Flames",
                            SatisDevamMi = true
                        },
                        new
                        {
                            Id = 20,
                            AlbumAdi = "Come Clarity",
                            CikisTarihi = new DateTime(2006, 2, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Fiyat = 170m,
                            Sanatci = "In Flames",
                            SatisDevamMi = true
                        },
                        new
                        {
                            Id = 21,
                            AlbumAdi = "A Sense of Purpose",
                            CikisTarihi = new DateTime(2008, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Fiyat = 180m,
                            Sanatci = "In Flames",
                            SatisDevamMi = true
                        },
                        new
                        {
                            Id = 22,
                            AlbumAdi = "Sounds of a Playground Fading",
                            CikisTarihi = new DateTime(2011, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Fiyat = 190m,
                            Sanatci = "In Flames",
                            SatisDevamMi = true
                        },
                        new
                        {
                            Id = 23,
                            AlbumAdi = "Siren Charms",
                            CikisTarihi = new DateTime(2014, 9, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Fiyat = 200m,
                            IndirimOrani = 10m,
                            Sanatci = "In Flames",
                            SatisDevamMi = true
                        },
                        new
                        {
                            Id = 24,
                            AlbumAdi = "Battles",
                            CikisTarihi = new DateTime(2016, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Fiyat = 190m,
                            Sanatci = "In Flames",
                            SatisDevamMi = true
                        },
                        new
                        {
                            Id = 25,
                            AlbumAdi = "I, the Mask",
                            CikisTarihi = new DateTime(2019, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Fiyat = 180m,
                            Sanatci = "In Flames",
                            SatisDevamMi = true
                        },
                        new
                        {
                            Id = 26,
                            AlbumAdi = "Foregone",
                            CikisTarihi = new DateTime(2023, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Fiyat = 170m,
                            Sanatci = "In Flames",
                            SatisDevamMi = true
                        },
                        new
                        {
                            Id = 27,
                            AlbumAdi = "Dance of December Souls",
                            CikisTarihi = new DateTime(1993, 12, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Fiyat = 100m,
                            Sanatci = "Katatonia",
                            SatisDevamMi = false
                        },
                        new
                        {
                            Id = 28,
                            AlbumAdi = "Brave Murder Day",
                            CikisTarihi = new DateTime(1996, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Fiyat = 110m,
                            Sanatci = "Katatonia",
                            SatisDevamMi = false
                        },
                        new
                        {
                            Id = 29,
                            AlbumAdi = "Discouraged Ones",
                            CikisTarihi = new DateTime(1998, 4, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Fiyat = 120m,
                            Sanatci = "Katatonia",
                            SatisDevamMi = true
                        },
                        new
                        {
                            Id = 30,
                            AlbumAdi = "Tonight's Decision",
                            CikisTarihi = new DateTime(1999, 8, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Fiyat = 130m,
                            Sanatci = "Katatonia",
                            SatisDevamMi = true
                        },
                        new
                        {
                            Id = 31,
                            AlbumAdi = "Last Fair Deal Gone Down",
                            CikisTarihi = new DateTime(2001, 5, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Fiyat = 140m,
                            Sanatci = "Katatonia",
                            SatisDevamMi = true
                        },
                        new
                        {
                            Id = 32,
                            AlbumAdi = "Viva Emptiness",
                            CikisTarihi = new DateTime(2003, 3, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Fiyat = 150m,
                            Sanatci = "Katatonia",
                            SatisDevamMi = true
                        },
                        new
                        {
                            Id = 33,
                            AlbumAdi = "The Great Cold Distance",
                            CikisTarihi = new DateTime(2006, 3, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Fiyat = 160m,
                            Sanatci = "Katatonia",
                            SatisDevamMi = true
                        },
                        new
                        {
                            Id = 34,
                            AlbumAdi = "Night Is the New Day",
                            CikisTarihi = new DateTime(2009, 11, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Fiyat = 170m,
                            Sanatci = "Katatonia",
                            SatisDevamMi = true
                        },
                        new
                        {
                            Id = 35,
                            AlbumAdi = "Dead End Kings",
                            CikisTarihi = new DateTime(2012, 8, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Fiyat = 180m,
                            Sanatci = "Katatonia",
                            SatisDevamMi = true
                        },
                        new
                        {
                            Id = 36,
                            AlbumAdi = "The Fall of Hearts",
                            CikisTarihi = new DateTime(2016, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Fiyat = 190m,
                            IndirimOrani = 10m,
                            Sanatci = "Katatonia",
                            SatisDevamMi = true
                        },
                        new
                        {
                            Id = 37,
                            AlbumAdi = "City Burials",
                            CikisTarihi = new DateTime(2020, 4, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Fiyat = 200m,
                            Sanatci = "Katatonia",
                            SatisDevamMi = true
                        },
                        new
                        {
                            Id = 38,
                            AlbumAdi = "Sky Void of Stars",
                            CikisTarihi = new DateTime(2023, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Fiyat = 190m,
                            Sanatci = "Katatonia",
                            SatisDevamMi = true
                        },
                        new
                        {
                            Id = 39,
                            AlbumAdi = "Nightmares as Extensions of the Waking State",
                            CikisTarihi = new DateTime(2025, 6, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Fiyat = 180m,
                            Sanatci = "Katatonia",
                            SatisDevamMi = true
                        });
                });

            modelBuilder.Entity("PlakDukkaniYonetimi.Core.Models.Yonetici", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("KullaniciAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sifre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Yoneticiler");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            KullaniciAdi = "admin",
                            Sifre = "8C6976E5B5410415BDE908BD4DEE15DFB167A9C873FC4BB8A81F6F2AB448A918"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
